# Generated by Django 6.0.3 on 2026-03-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField()),
                ('price', models.IntegerField()),
                ('pic', models.URLField(blank=True, null=True)),
                ('creator', models.CharField()),
            ],
        ),
    ]
